<a href="https://colab.research.google.com/github/Slsk-98/HatespeechDetection/blob/main/tfidf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
dataset=pd.read_csv('/content/drive/My Drive/Hate Speech Detection/Project Codes/naive inp.csv')
#X,y=df['tweet'],df['class']

In [ ]:
def removeSpaces(dataset):
  ret = []
  for data in dataset:
    ret.append(data.strip())

  return ret

X = dataset.drop('class',axis=1)
x = list(X["tweet"])
X = removeSpaces(x)
y = list(dataset['class'])

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
import nltk
#nltk.download('stopwords')
vectorizer=CountVectorizer()
X = vectorizer.fit_transform(X)

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidfconverter=TfidfTransformer()
X=tfidfconverter.fit_transform(X)

In [ ]:
y_ = np.array(y)
X = X.toarray()
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y_,test_size=0.3,random_state=4)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
y_pred=classifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[1076    1  202]
 [  53   53  340]
 [ 190   25 5495]]
              precision    recall  f1-score   support

           0       0.82      0.84      0.83      1279
           1       0.67      0.12      0.20       446
           2       0.91      0.96      0.94      5710

    accuracy                           0.89      7435
   macro avg       0.80      0.64      0.66      7435
weighted avg       0.88      0.89      0.87      7435

0.8909213180901143


In [ ]:
import os
os.chdir('/content/drive/My Drive/Hate Speech Detection/Project Codes/Voting_input')
from joblib import dump,load
dump(classifier,'rf_tfidf.joblib')

['rf_tfidf.joblib']